server {
  listen 80;
  server_name login.solutions.local;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  http2 on;

  server_name login.solutions.local;

  ssl_certificate     /etc/ssl/login.solutions.local.pem;
  ssl_certificate_key /etc/ssl/login.solutions.local-key.pem;

  # =========================
  # MARCAJES WEB (Vite + HMR)
  # =========================
  location /marcajes/ {
    proxy_pass http://marcajes-web:5173;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
  }

  # =========================
  # ADMIN WEB (Vite + HMR)
  # =========================
  location /admin/ {
    proxy_pass http://admin-web:5174;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
  }

  # =========================
  # USER SERVICE API
  # (el servicio ya monta /user-service/api)
  # =========================
  location /user-service/api/ {
    proxy_pass http://user-service:4000;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
  }

  # =========================
  # MARCAJES API
  # (validaste que /health existe en raíz)
  # =========================
  location /marcajes-api/api/ {
  proxy_pass http://marcajes-api:4100/marcajes-api/api/;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto https;
  }
}
